#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[195] =
    {   0,
        0,    0,   19,   17,    2,    1,   17,   17,    6,   17,
        4,    3,   17,   17,   17,    5,   12,   17,    0,   17,
       17,    0,   14,    0,   17,   17,   17,    9,    8,    7,
        0,   13,   13,   17,   17,    0,    0,   17,   16,   17,
       12,   12,   12,   14,   14,    0,   13,   13,   13,   17,
       17,    0,   16,    0,   17,   17,    0,    0,   17,   15,
       10,   13,   13,   17,    0,   16,    0,   16,   13,   13,
       13,   17,   17,   12,   12,   12,   12,   13,   13,   13,
       13,   17,   13,    0,   14,   16,   16,    0,   13,   13,
       13,   17,   15,    0,   15,   13,   13,   17,   13,   15,

       15,   15,   15,   15,   13,   13,   13,   17,   13,    0,
       13,   16,   17,   12,   12,   12,   12,   12,   13,   13,
       13,   13,   17,   13,    0,   16,   15,   13,   15,   15,
       13,   13,   17,   13,    0,   13,   15,   13,   13,   13,
       15,   15,   13,   13,   13,   15,   17,   15,   13,   15,
       15,   13,   15,   13,   15,   15,   15,   15,   15,   15,
       17,   15,   15,   13,   15,   15,   15,   15,   13,   13,
       13,   15,   13,   15,   13,   13,   13,   15,   13,   11,
       15,   13,   15,   13,   15,   13,   13,   15,   15,   13,
       11,   13,   15,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    7,    1,    8,
        9,    1,    1,    1,    1,    1,    1,    1,    1,   10,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
        1,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   13,    1,    1,    1,   14,    1,    1,   15,    1,

       16,    1,    1,    1,    1,    1,    1,    1,    1,   17,
       18,    1,    1,   19,   20,   17,   21,    1,    1,    1,
        1,    1,   22,   23,   24,   25,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[26] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    1,    1,    6,    1,    1,    1,
        1,    1,    5,    1,    1
    } ;

static const flex_int16_t yy_base[259] =
    {   0,
        0,    0,  250,   14, 2073, 2073,   36,   52,   20,   21,
       22,   38,   74,   96,   39,  236,   23,   31,  227,  118,
      140,  233,   44,  162,  174,  196,  218,  224,  220,   49,
        0,   56,  219,    0,  241,  212,  263,  276,   50,   59,
       70,  211,  298, 2073,  200,   68,  320,  342,   76,  354,
      376,  195,    0,  398,  410,  432,  170,   82,  455,  478,
      179,   89,  159,  500,  522, 2073,  100,  155,  538,  560,
       92,  573,  105,  595,  113,  152,   84,  146,  611,  116,
      633,  645,  144,  129,    0,  147,  661,  134,  673,  695,
      707,  729,  149,  750,  148,  773,  136,  796,  819,  841,

      142,  109,  156,  863,  110,  885,  907,  920,  158,  170,
      105,    0,  125,    0,  170,  103,  936,  958,  974,    0,
        0,  986,  998, 1014,  171, 1026,   48,  183, 1048, 1068,
     1084,  188, 1107, 1123, 1144,  193, 1167,    0,   89,  201,
     1189, 1205,    0,  209,   72, 1228,  194,  211, 1250, 1270,
     1286, 1309, 1330, 1352, 1375,  212,   70, 1398, 1421,    0,
      217,  222,   84, 1444, 1467, 1489,  221, 1512, 1535,   65,
     1558, 1581,    0,    0,    0, 1597,   41, 1620,    0,    0,
      223, 1643, 1665,  246,   33,    0,  255,   12,   10,    0,
        0,    9,    0, 2073, 1689, 1695, 1701, 1707, 1713, 1719,

     1725, 1731, 1737, 1743, 1749, 1755, 1760, 1766, 1772, 1778,
     1784, 1790, 1796, 1802, 1808, 1814, 1820, 1826, 1832, 1838,
     1844, 1850, 1856, 1862, 1868, 1874, 1880, 1886, 1892, 1898,
     1904, 1910, 1916, 1922, 1928, 1934, 1940, 1946, 1952, 1958,
     1964, 1970, 1976, 1982, 1988, 1994, 2000, 2006, 2012, 2018,
     2024, 2030, 2036, 2042, 2048, 2054, 2060, 2066
    } ;

static const flex_int16_t yy_def[259] =
    {   0,
      194,    1,  194,  195,  194,  194,  196,  195,    8,    8,
        8,  197,  198,  199,    8,  197,  200,    8,  197,  198,
      196,  201,    8,  202,  203,  204,  205,  197,  197,  197,
      206,  207,  208,  209,  199,  210,  211,  212,    8,    8,
      200,  213,  214,  194,  197,  215,  216,  217,  207,  218,
      204,  219,   51,  220,  221,  205,  222,  223,  224,  225,
      197,  207,  208,  207,  208,  194,  226,  197,  227,  228,
      207,  229,    8,  230,  231,  232,  233,  208,  216,  207,
      217,   79,  208,  217,  209,  219,  220,  234,  235,  236,
      235,  237,  238,  239,  240,  241,  242,  243,  244,  225,

      238,  100,  240,  245,  208,  227,  228,  106,  207,  228,
      208,  209,    8,  246,  231,  232,  231,  232,  236,   91,
       91,  236,   91,  236,  236,  237,  238,  247,  240,  248,
      241,  242,  131,  244,  242,  247,  249,  134,  134,  247,
      134,  250,  134,  247,  134,  249,    8,  251,  247,  247,
      252,  247,  249,  253,  250,  251,  155,  252,  254,  100,
        8,  251,  238,  255,  252,  256,  240,  257,  253,  169,
      255,  169,  134,  155,  169,  255,  169,  257,  134,  258,
      251,  255,  255,  247,  165,  182,  247,  178,  153,  169,
      258,  182,  178,    0,  194,  194,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194
    } ;

static const flex_int16_t yy_nxt[2099] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,    4,   10,
       11,   12,   13,   14,    4,    4,    4,    4,    4,   15,
        4,    4,   16,    4,   17,   19,   20,   18,   18,   18,
      171,  146,   28,  193,   42,   43,   19,   22,   18,   22,
       23,   18,   18,   18,   29,   42,   18,   24,   25,   30,
       31,   18,   18,  127,  158,   61,   40,   18,   24,   26,
       18,   31,  190,   19,   20,   18,   18,   63,   64,  148,
       33,   18,   78,   27,   19,   33,   33,   33,   63,   73,
       18,   42,   43,   57,   22,   33,  190,   63,   64,  127,
       34,  174,   42,  154,   94,  114,   33,   36,   63,   36,

       63,   64,   33,   63,   64,   95,  114,   37,   38,   39,
      154,   63,   18,  105,   63,  118,   36,   65,   37,   33,
       33,   33,   65,  113,  116,  117,   18,   63,   64,   33,
      142,   63,   18,   83,   34,  116,   33,   57,   63,  147,
       33,   22,  119,   22,   23,   22,   18,  127,  135,  101,
       52,   24,   25,  129,  127,   86,   65,  101,   65,  136,
      130,  129,   24,   22,  118,   22,   45,   31,  130,   63,
       64,   65,   63,   63,   46,   48,   33,   48,   49,  124,
       63,  116,  117,  111,  101,   48,   36,   52,  149,   57,
       50,   31,  116,   93,  101,  150,   48,   52,  149,   52,

      135,   18,  101,   86,   53,  150,  149,   54,   55,  161,
      101,  136,   31,  150,  149,   18,  162,  162,   54,   57,
      180,  150,  101,   74,   18,   66,  129,  162,  162,   58,
       59,   65,   31,  130,  163,  163,   31,   44,   18,   31,
       58,   60,   36,  181,   36,  163,  163,  101,   31,  194,
      194,  149,   37,   38,   39,  194,  101,  194,  150,  194,
      149,  194,  194,   37,   36,  194,   36,  150,  194,  194,
      194,  194,  194,  194,  194,   67,   68,   70,   33,   70,
      194,  194,  194,  194,  194,  194,  194,   70,  194,   71,
      194,  194,   72,  194,  194,  194,  194,  194,   70,   33,

       33,   33,  194,  194,  194,  194,  194,  194,  194,   76,
      194,  194,  194,  194,   77,  194,  194,  194,  194,  194,
       76,   22,  194,   22,   80,  194,  194,  194,  194,  194,
      194,   81,   82,  194,  194,  194,  194,  194,  194,  194,
      194,  194,   81,   22,  194,   22,   83,  194,  194,  194,
      194,  194,  194,  194,   84,   22,  194,   22,   85,  194,
      194,  194,  194,  194,  194,   22,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,   22,   52,  194,   52,
      194,  194,  194,  194,   53,  194,  194,   54,   55,  194,
      194,  194,  194,  194,  194,  194,  194,  194,   54,   52,

      194,   52,  194,  194,  194,  194,   87,  194,  194,  194,
       88,   90,   33,   90,  194,  194,  194,  194,   91,  194,
      194,   90,  194,  194,  194,  194,   92,  194,  194,  194,
      194,  194,   90,   57,  194,  194,  194,  194,  194,  194,
      194,  194,  194,   58,   59,  194,  194,  194,  194,  194,
      194,  194,  194,  194,   58,   60,   97,   33,   33,  194,
      194,  194,  194,  194,  194,  194,   97,  194,  194,  194,
      194,   98,  194,  194,  194,  194,  194,   97,   99,  101,
      194,  194,  194,  102,  194,  194,  194,  194,  194,  103,
      104,  194,  194,  194,  194,  194,  194,  194,  194,  194,

      103,   63,   63,   63,  194,  194,  194,  194,  194,  194,
      194,   63,  194,  194,  194,  194,   34,  194,  194,  194,
      194,  194,   63,   63,   63,   63,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,   36,
      194,   36,  194,  194,  194,  194,  194,  194,  194,  107,
      108,  109,  194,  194,  194,  194,  194,  194,  194,  194,
      107,   36,  194,   36,  194,  194,  194,  194,  194,  194,
      194,  194,  110,  111,   36,  194,   36,  194,  194,  194,
      194,  194,  194,  194,   36,  194,  112,  194,  194,  194,
      194,  194,  194,  194,  194,   36,   33,   33,   33,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  114,   22,  194,   22,   80,  194,  194,  194,  194,
      194,  194,   81,   82,  194,  194,  194,  194,  194,  194,
      194,  194,  194,   81,   22,  194,   22,   83,  194,  194,
      194,  194,  194,  194,  194,   84,   81,   63,   81,  194,
      194,  194,  194,  194,  194,  194,  194,   79,  194,  194,
      194,   50,   52,  194,   52,  194,  194,  194,  194,   87,
      194,  194,  194,   88,   52,  194,   52,  194,  194,  194,
      194,  121,  194,  194,  122,  123,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  122,   52,  194,   52,  194,

      194,  194,  194,  124,  194,  194,  194,  125,   52,  194,
       52,  194,  194,  194,  194,  121,  194,  194,  122,  123,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  122,
       52,  194,   52,  194,  194,  194,  194,  126,  194,  194,
       52,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,   52,   33,   33,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,   57,  194,  194,  194,
      194,  194,  194,  128,   57,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  132,  133,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  132,  134,   57,  194,  194,

      194,  194,  194,  194,  194,  194,  194,   57,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,   57,  137,
      101,  194,  194,  194,  139,  194,  194,  194,  194,  194,
      140,  141,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  140,  101,  194,  194,  194,  102,  194,  194,  194,
      194,  194,  103,  104,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  103,  144,   33,   33,  194,  145,  194,
      194,  194,  194,  194,  144,  194,  194,  194,  194,  146,
      194,  194,  194,  194,  194,  144,   36,  194,   36,  194,
      194,  194,  194,  194,  194,  194,  107,  108,  109,  194,

      194,  194,  194,  194,  194,  194,  194,  107,   36,  194,
       36,  194,  194,  194,  194,  194,  194,  194,  194,  110,
      111,  107,   63,  107,  194,  194,  194,  194,  194,  194,
      194,  194,  106,  194,  194,  194,   72,   63,   63,   63,
      194,  194,  194,  194,  194,  194,  194,  116,  194,  194,
      194,  194,   77,  194,  194,  194,  194,  194,  116,   63,
       63,   63,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  114,   52,  194,   52,  194,  194,
      194,  194,  124,  194,  194,  194,  125,   52,  194,   52,
      194,  194,  194,  194,  124,  194,  194,  194,  125,  122,

       63,  122,  194,  194,  194,  194,  194,  194,  194,  194,
      120,  194,  194,  194,   92,   52,  194,   52,  194,  194,
      194,  194,  124,  194,  194,  194,  125,   52,  194,   52,
      194,  194,  194,  194,  126,  194,  194,   52,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,   52,  101,
      194,  194,  194,  129,  194,  194,  194,  194,  194,  194,
      130,  194,  194,  194,  194,  194,  194,  194,  194,  151,
       33,   33,  194,  152,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  101,   57,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  132,  133,  194,  194,  194,

      194,  194,  194,  194,  194,  194,  132,  134,  132,   63,
       63,  194,  194,  194,  194,  194,  194,  194,  194,  131,
      194,  194,  194,   98,  101,  194,  194,  194,  139,  194,
      194,  194,  194,  194,  140,  141,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  140,   63,   63,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
       57,  194,  194,  194,  194,  194,  194,  136,  101,  194,
      194,  194,  153,  194,  194,  194,  194,  194,  101,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  101,
      140,   63,   63,  194,  194,  194,  194,  194,  194,  194,

      194,  138,  194,  194,  194,  146,  156,  194,  194,  194,
      157,  194,  194,  194,  194,  194,  158,  159,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  158,  160,  101,
      194,  194,  194,  153,  194,  194,  194,  194,  194,  101,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      101,  101,  194,  194,  194,  149,  194,  194,  194,  194,
      194,  194,  150,  194,  194,  194,  194,  194,  194,  194,
      194,  164,   63,   63,  194,  149,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  101,  156,  194,  194,
      194,  165,  194,  194,  194,  194,  194,  194,  166,  194,

      194,  194,  194,  194,  194,  194,  194,  194,  194,  167,
      101,  194,  194,  194,  149,  194,  194,  194,  194,  194,
      194,  150,  194,  194,  194,  194,  194,  194,  194,  194,
      164,  101,  194,  194,  194,  153,  194,  194,  194,  194,
      194,  101,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  168,  101,  156,  194,  194,  194,  170,  194,  194,
      194,  194,  194,  171,  172,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  171,  173,  156,  194,  194,  194,
      157,  194,  194,  194,  194,  194,  158,  159,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  158,  160,  156,

      194,  194,  194,  165,  194,  194,  194,  194,  194,  194,
      166,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  167,  176,   33,   33,  194,  177,  194,  194,  194,
      194,  194,  176,  194,  194,  194,  194,  178,  194,  194,
      194,  194,  194,  176,  179,  156,  194,  194,  194,  182,
      194,  194,  194,  194,  194,  194,  183,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  184,  156,  194,
      194,  194,  165,  194,  194,  194,  194,  194,  194,  166,
      194,  194,  194,  194,  194,  194,  194,  194,  185,  194,
      167,   33,   33,  194,  186,  194,  194,  194,  194,  194,

      194,  194,  194,  194,  194,  156,  194,  194,  194,  194,
      194,  194,  187,  156,  194,  194,  194,  188,  194,  194,
      194,  194,  194,  156,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  156,  189,  156,  194,  194,  194,
      170,  194,  194,  194,  194,  194,  171,  172,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  171,  173,  156,
      194,  194,  194,  182,  194,  194,  194,  194,  194,  194,
      183,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  184,  171,   63,   63,  194,  194,  194,  194,  194,
      194,  194,  194,  169,  194,  194,  194,  178,  156,  194,

      194,  194,  182,  194,  194,  194,  194,  194,  194,  183,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      184,  156,  194,  194,  194,  188,  194,  194,  194,  194,
      194,  156,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  156,  189,  156,  194,  194,  194,  182,  194,
      194,  194,  194,  194,  194,  183,  194,  194,  194,  194,
      194,  194,  194,  194,  192,  194,  184,   63,   63,  194,
      182,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  156,  194,  194,  194,  194,  194,  194,  184,   18,
      194,  194,  194,   18,   18,   21,   21,  194,   21,   21,

       21,   19,  194,  194,  194,   19,   19,   32,   32,   32,
       32,   32,   32,   35,   35,  194,   35,   35,   35,   41,
      194,  194,  194,   41,   41,   22,   22,  194,   22,   22,
       22,   24,   24,  194,   24,   24,   24,   47,   47,   47,
       47,   47,   47,   51,   51,  194,   51,   51,   51,   56,
       56,  194,  194,   56,   56,   33,   33,   33,   33,   33,
       62,  194,  194,  194,   62,   62,   63,  194,  194,  194,
       63,   63,   34,  194,  194,  194,  194,   34,   36,   36,
      194,   36,   36,   36,   37,   37,  194,   37,   37,   37,
       69,   69,   69,   69,   69,   69,   42,  194,  194,  194,

       42,   42,   75,   75,   75,   75,   75,   75,   48,   48,
       48,   48,   48,   48,   79,   79,  194,   79,   79,   79,
       81,   81,  194,   81,   81,   81,   50,   50,  194,   50,
       50,   50,   52,   52,  194,   52,   52,   52,   54,   54,
      194,   54,   54,   54,   89,   89,   89,   89,   89,   89,
       57,   57,  194,  194,   57,   57,   58,   58,  194,  194,
       58,   58,   96,   96,   96,   96,   96,   96,  100,  100,
      194,  194,  100,  100,   70,   70,   70,   70,   70,   70,
      106,  106,  194,  106,  106,  106,  107,  107,  194,  107,
      107,  107,   72,   72,  194,   72,   72,   72,   76,   76,

       76,   76,   76,   76,  115,  194,  194,  194,  115,  115,
      116,  194,  194,  194,  116,  116,   77,  194,  194,  194,
       77,   77,   90,   90,   90,   90,   90,   90,  120,  120,
      194,  120,  120,  120,  122,  122,  194,  122,  122,  122,
       92,   92,  194,   92,   92,   92,  101,  101,  194,  194,
      101,  101,   97,   97,   97,   97,   97,   97,  103,  103,
      194,  194,  103,  103,  131,  131,  194,  194,  131,  131,
      132,  132,  194,  194,  132,  132,   98,   98,  194,  194,
       98,   98,  138,  138,  194,  194,  138,  138,  143,  143,
      143,  143,  143,  143,  114,  194,  194,  194,  114,  114,

      140,  140,  194,  194,  140,  140,  144,  144,  144,  144,
      144,  144,  146,  146,  194,  194,  146,  146,  155,  155,
      194,  194,  155,  155,  156,  156,  194,  194,  156,  156,
      158,  158,  194,  194,  158,  158,  169,  169,  194,  194,
      169,  169,  175,  175,  175,  175,  175,  175,  171,  171,
      194,  194,  171,  171,  176,  176,  176,  176,  176,  176,
      178,  178,  194,  194,  178,  178,  191,  191,  194,  191,
      191,  191,    3,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194

    } ;

static const flex_int16_t yy_chk[2099] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    9,   10,   11,
      192,  189,   10,  188,   17,   17,    4,    7,   18,    7,
        7,    9,   10,   11,   12,   17,   15,    7,    7,   12,
       12,   23,   18,  127,  185,   30,   15,   39,    7,    8,
       15,   30,  177,    8,    8,   23,   40,   32,   32,  127,
       46,   39,   46,    8,    8,   13,   13,   13,   32,   40,
       40,   41,   41,   58,   46,   13,  170,   49,   49,  163,
       13,  157,   41,  145,   58,   77,   13,   14,   49,   14,

       62,   62,   67,   71,   71,   58,   77,   14,   14,   14,
      139,   62,   73,   67,   71,  116,   67,  111,   14,   20,
       20,   20,  105,   73,   75,   75,   73,   80,   80,   20,
      102,   84,  113,   84,   20,   75,   88,   97,   80,  113,
       20,   21,   88,   21,   21,   84,  113,  101,   97,   95,
       88,   21,   21,   95,   93,   86,   83,  103,   78,   97,
       95,  103,   21,   24,   76,   24,   24,   68,  103,  109,
      109,   63,  110,  125,   24,   25,   25,   25,   25,  125,
      109,  115,  115,  110,  128,   25,  110,  125,  128,  132,
       25,   61,  115,   57,  136,  128,   25,   26,  136,   26,

      132,  147,  140,   52,   26,  136,  140,   26,   26,  147,
      144,  132,   45,  140,  144,  147,  148,  156,   26,   27,
      161,  144,  167,   42,  161,   36,  167,  162,  181,   27,
       27,   33,   29,  167,  148,  156,   28,   22,  161,   19,
       27,   27,   35,  162,   35,  162,  181,  184,   16,    3,
        0,  184,   35,   35,   35,    0,  187,    0,  184,    0,
      187,    0,    0,   35,   37,    0,   37,  187,    0,    0,
        0,    0,    0,    0,    0,   37,   37,   38,   38,   38,
        0,    0,    0,    0,    0,    0,    0,   38,    0,   38,
        0,    0,   38,    0,    0,    0,    0,    0,   38,   43,

       43,   43,    0,    0,    0,    0,    0,    0,    0,   43,
        0,    0,    0,    0,   43,    0,    0,    0,    0,    0,
       43,   47,    0,   47,   47,    0,    0,    0,    0,    0,
        0,   47,   47,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   47,   48,    0,   48,   48,    0,    0,    0,
        0,    0,    0,    0,   48,   50,    0,   50,   50,    0,
        0,    0,    0,    0,    0,   50,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   50,   51,    0,   51,
        0,    0,    0,    0,   51,    0,    0,   51,   51,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,   54,

        0,   54,    0,    0,    0,    0,   54,    0,    0,    0,
       54,   55,   55,   55,    0,    0,    0,    0,   55,    0,
        0,   55,    0,    0,    0,    0,   55,    0,    0,    0,
        0,    0,   55,   56,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   56,   56,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   56,   56,   59,   59,   59,    0,
        0,    0,    0,    0,    0,    0,   59,    0,    0,    0,
        0,   59,    0,    0,    0,    0,    0,   59,   59,   60,
        0,    0,    0,   60,    0,    0,    0,    0,    0,   60,
       60,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       60,   64,   64,   64,    0,    0,    0,    0,    0,    0,
        0,   64,    0,    0,    0,    0,   64,    0,    0,    0,
        0,    0,   64,   65,   65,   65,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   65,   69,
        0,   69,    0,    0,    0,    0,    0,    0,    0,   69,
       69,   69,    0,    0,    0,    0,    0,    0,    0,    0,
       69,   70,    0,   70,    0,    0,    0,    0,    0,    0,
        0,    0,   70,   70,   72,    0,   72,    0,    0,    0,
        0,    0,    0,    0,   72,    0,   72,    0,    0,    0,
        0,    0,    0,    0,    0,   72,   74,   74,   74,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   74,   79,    0,   79,   79,    0,    0,    0,    0,
        0,    0,   79,   79,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   79,   81,    0,   81,   81,    0,    0,
        0,    0,    0,    0,    0,   81,   82,   82,   82,    0,
        0,    0,    0,    0,    0,    0,    0,   82,    0,    0,
        0,   82,   87,    0,   87,    0,    0,    0,    0,   87,
        0,    0,    0,   87,   89,    0,   89,    0,    0,    0,
        0,   89,    0,    0,   89,   89,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   89,   90,    0,   90,    0,

        0,    0,    0,   90,    0,    0,    0,   90,   91,    0,
       91,    0,    0,    0,    0,   91,    0,    0,   91,   91,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   91,
       92,    0,   92,    0,    0,    0,    0,   92,    0,    0,
       92,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   92,   94,   94,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   94,    0,    0,    0,
        0,    0,    0,   94,   96,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   96,   96,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   96,   96,   98,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   98,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   98,   98,
       99,    0,    0,    0,   99,    0,    0,    0,    0,    0,
       99,   99,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   99,  100,    0,    0,    0,  100,    0,    0,    0,
        0,    0,  100,  100,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  100,  104,  104,  104,    0,  104,    0,
        0,    0,    0,    0,  104,    0,    0,    0,    0,  104,
        0,    0,    0,    0,    0,  104,  106,    0,  106,    0,
        0,    0,    0,    0,    0,    0,  106,  106,  106,    0,

        0,    0,    0,    0,    0,    0,    0,  106,  107,    0,
      107,    0,    0,    0,    0,    0,    0,    0,    0,  107,
      107,  108,  108,  108,    0,    0,    0,    0,    0,    0,
        0,    0,  108,    0,    0,    0,  108,  117,  117,  117,
        0,    0,    0,    0,    0,    0,    0,  117,    0,    0,
        0,    0,  117,    0,    0,    0,    0,    0,  117,  118,
      118,  118,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  118,  119,    0,  119,    0,    0,
        0,    0,  119,    0,    0,    0,  119,  122,    0,  122,
        0,    0,    0,    0,  122,    0,    0,    0,  122,  123,

      123,  123,    0,    0,    0,    0,    0,    0,    0,    0,
      123,    0,    0,    0,  123,  124,    0,  124,    0,    0,
        0,    0,  124,    0,    0,    0,  124,  126,    0,  126,
        0,    0,    0,    0,  126,    0,    0,  126,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  126,  129,
        0,    0,    0,  129,    0,    0,    0,    0,    0,    0,
      129,    0,    0,    0,    0,    0,    0,    0,    0,  129,
      130,  130,    0,  130,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  130,  131,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  131,  131,    0,    0,    0,

        0,    0,    0,    0,    0,    0,  131,  131,  133,  133,
      133,    0,    0,    0,    0,    0,    0,    0,    0,  133,
        0,    0,    0,  133,  134,    0,    0,    0,  134,    0,
        0,    0,    0,    0,  134,  134,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  134,  135,  135,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      135,    0,    0,    0,    0,    0,    0,  135,  137,    0,
        0,    0,  137,    0,    0,    0,    0,    0,  137,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  137,
      141,  141,  141,    0,    0,    0,    0,    0,    0,    0,

        0,  141,    0,    0,    0,  141,  142,    0,    0,    0,
      142,    0,    0,    0,    0,    0,  142,  142,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  142,  142,  146,
        0,    0,    0,  146,    0,    0,    0,    0,    0,  146,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      146,  149,    0,    0,    0,  149,    0,    0,    0,    0,
        0,    0,  149,    0,    0,    0,    0,    0,    0,    0,
        0,  149,  150,  150,    0,  150,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  150,  151,    0,    0,
        0,  151,    0,    0,    0,    0,    0,    0,  151,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  151,
      152,    0,    0,    0,  152,    0,    0,    0,    0,    0,
        0,  152,    0,    0,    0,    0,    0,    0,    0,    0,
      152,  153,    0,    0,    0,  153,    0,    0,    0,    0,
        0,  153,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  153,  153,  154,    0,    0,    0,  154,    0,    0,
        0,    0,    0,  154,  154,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  154,  154,  155,    0,    0,    0,
      155,    0,    0,    0,    0,    0,  155,  155,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  155,  155,  158,

        0,    0,    0,  158,    0,    0,    0,    0,    0,    0,
      158,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  158,  159,  159,  159,    0,  159,    0,    0,    0,
        0,    0,  159,    0,    0,    0,    0,  159,    0,    0,
        0,    0,    0,  159,  159,  164,    0,    0,    0,  164,
        0,    0,    0,    0,    0,    0,  164,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  164,  165,    0,
        0,    0,  165,    0,    0,    0,    0,    0,    0,  165,
        0,    0,    0,    0,    0,    0,    0,    0,  165,    0,
      165,  166,  166,    0,  166,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,  166,    0,    0,    0,    0,
        0,    0,  166,  168,    0,    0,    0,  168,    0,    0,
        0,    0,    0,  168,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  168,  168,  169,    0,    0,    0,
      169,    0,    0,    0,    0,    0,  169,  169,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  169,  169,  171,
        0,    0,    0,  171,    0,    0,    0,    0,    0,    0,
      171,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  171,  172,  172,  172,    0,    0,    0,    0,    0,
        0,    0,    0,  172,    0,    0,    0,  172,  176,    0,

        0,    0,  176,    0,    0,    0,    0,    0,    0,  176,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      176,  178,    0,    0,    0,  178,    0,    0,    0,    0,
        0,  178,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  178,  178,  182,    0,    0,    0,  182,    0,
        0,    0,    0,    0,    0,  182,    0,    0,    0,    0,
        0,    0,    0,    0,  182,    0,  182,  183,  183,    0,
      183,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  183,    0,    0,    0,    0,    0,    0,  183,  195,
        0,    0,    0,  195,  195,  196,  196,    0,  196,  196,

      196,  197,    0,    0,    0,  197,  197,  198,  198,  198,
      198,  198,  198,  199,  199,    0,  199,  199,  199,  200,
        0,    0,    0,  200,  200,  201,  201,    0,  201,  201,
      201,  202,  202,    0,  202,  202,  202,  203,  203,  203,
      203,  203,  203,  204,  204,    0,  204,  204,  204,  205,
      205,    0,    0,  205,  205,  206,  206,  206,  206,  206,
      207,    0,    0,    0,  207,  207,  208,    0,    0,    0,
      208,  208,  209,    0,    0,    0,    0,  209,  210,  210,
        0,  210,  210,  210,  211,  211,    0,  211,  211,  211,
      212,  212,  212,  212,  212,  212,  213,    0,    0,    0,

      213,  213,  214,  214,  214,  214,  214,  214,  215,  215,
      215,  215,  215,  215,  216,  216,    0,  216,  216,  216,
      217,  217,    0,  217,  217,  217,  218,  218,    0,  218,
      218,  218,  219,  219,    0,  219,  219,  219,  220,  220,
        0,  220,  220,  220,  221,  221,  221,  221,  221,  221,
      222,  222,    0,    0,  222,  222,  223,  223,    0,    0,
      223,  223,  224,  224,  224,  224,  224,  224,  225,  225,
        0,    0,  225,  225,  226,  226,  226,  226,  226,  226,
      227,  227,    0,  227,  227,  227,  228,  228,    0,  228,
      228,  228,  229,  229,    0,  229,  229,  229,  230,  230,

      230,  230,  230,  230,  231,    0,    0,    0,  231,  231,
      232,    0,    0,    0,  232,  232,  233,    0,    0,    0,
      233,  233,  234,  234,  234,  234,  234,  234,  235,  235,
        0,  235,  235,  235,  236,  236,    0,  236,  236,  236,
      237,  237,    0,  237,  237,  237,  238,  238,    0,    0,
      238,  238,  239,  239,  239,  239,  239,  239,  240,  240,
        0,    0,  240,  240,  241,  241,    0,    0,  241,  241,
      242,  242,    0,    0,  242,  242,  243,  243,    0,    0,
      243,  243,  244,  244,    0,    0,  244,  244,  245,  245,
      245,  245,  245,  245,  246,    0,    0,    0,  246,  246,

      247,  247,    0,    0,  247,  247,  248,  248,  248,  248,
      248,  248,  249,  249,    0,    0,  249,  249,  250,  250,
        0,    0,  250,  250,  251,  251,    0,    0,  251,  251,
      252,  252,    0,    0,  252,  252,  253,  253,    0,    0,
      253,  253,  254,  254,  254,  254,  254,  254,  255,  255,
        0,    0,  255,  255,  256,  256,  256,  256,  256,  256,
      257,  257,    0,    0,  257,  257,  258,  258,    0,  258,
      258,  258,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  194,  194

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[19] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 10 "shell.l"

#include <cstring>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include "y.tab.hh"
#include "shell.hh"
#include <sys/types.h>
#include <sys/wait.h>
#include <string.h>

#define MAX_INCLUDE_DEPTH 10
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;
FILE *temp;

static  void yyunput (int c,char *buf_ptr  );

void myunputc(int c) {
  unput(c);
}

extern "C" char * read_line();

int mygetc(FILE * f) {
  static char *p;
  char ch;

  if (!isatty(0)) {
    return getc(f);
  }

  if (p==NULL || *p == 0) {
    char * s = read_line();
    p =s;
  }
  ch = *p;
  p++;

  return ch;
}

#undef getc
#define getc(f) mygetc(f)

#line 1062 "lex.yy.cc"
#line 1063 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 59 "shell.l"


#line 1283 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 195 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2073 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 61 "shell.l"
{
  return NEWLINE;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "shell.l"
{
  return GREAT;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 73 "shell.l"
{
  return LESS;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "shell.l"
{
  return PIPE;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 81 "shell.l"
{
  return AMPERSAND;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 85 "shell.l"
{
  return GREATGREAT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "shell.l"
{
  return GREATAND;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "shell.l"
{
  return TWOGREAT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "shell.l"
{
  return GREATGREATAND;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "shell.l"
{
  char *file = strchr(yytext, ' ') + 1;
  include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
  temp = yyin;
  yyin = fopen(file, "r");

  if (!yyin) {
    perror("fopen source");
  } else {
    yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
    yyparse();
    if (--include_stack_ptr < 0) {
      yyrestart(stdin);
    } else {
      yy_delete_buffer(YY_CURRENT_BUFFER);
      yy_switch_to_buffer(include_stack[include_stack_ptr]);
    }
  }
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 122 "shell.l"
{
  // TILDA 
  std::string str = std::string(yytext);
  std::string home = getenv("HOME");
  if (str.size() == 1) {
    yylval.cpp_string = new std::string(home);
  } 
  else {
    if (str[1] == '/') {
      str = home + str.substr(1, -1);
    } 
    else {
      str = std::string("/homes/") + str.substr(1,-1);
    }
    yylval.cpp_string = new std::string(str);
  }
  return WORD;
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 141 "shell.l"
{
 // escape char
  std::string str = std::string(yytext);
  std::size_t found = str.find('\\');
  while(found!=-1) {
    str = str.substr(0,found) + str.substr(found+1,std::string::npos);
    found = str.find('\\', found+1);
  }
  yylval.cpp_string = new std::string(str);
  return WORD;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 154 "shell.l"
{
// quotes
  std::string str = std::string(yytext);
  str = str.substr(1,str.size()-2);
  yylval.cpp_string = new std::string(str);
  return WORD;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 162 "shell.l"
{
 // env var expansion stuff
  std::string str = std::string(yytext);
  std::string result = "";
  std::size_t found = str.find('$');
  while(found!=-1) {
    std::string component;
    result += str.substr(0, found);
    if (str[found+1] == '{') {
      std::size_t end = str.find('}');
      if (end != -1) {
        component = str.substr(found+2, end-found-2);
        if (getenv(component.c_str())) result += getenv(component.c_str());
        else result += component;      
        str = str.substr(end+1,-1);
      }
    }
    found = str.find('$');
  }
  result += str;
  yylval.cpp_string = new std::string(result);
  return WORD;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 186 "shell.l"
{
// backtick sub
  std::string str = std::string(yytext);
  if (str.at(0) == '$') {
    str = str.substr(1,str.size()-1);
  }
  str = str.substr(1,str.size()-2);
  str += "\nexit\n";
  //printf("str : %s",str.c_str());

  int pin[2], pout[2], tmpin, tmpout;
  tmpin = dup(0); tmpout = dup(1);
  pipe(pin); pipe(pout);

  dup2(pin[0], 0);
  dup2(pout[1], 1);
  close(pin[0]);
  close(pout[1]);

  write(pin[1], str.c_str(), str.size());
  close(pin[1]);

  int ret = fork();
  if (ret==0) {
    char ** args = new char*[2];
    args[0] = (char*)"/proc/self/exe";
    args[1] = NULL;
    execvp(args[0], args);
    perror("execvp(subshell)");
    exit(1);
  } else if (ret < 0) {
    perror("fork");
    exit(1);
  } else {

    waitpid(ret, NULL, 0);

    dup2(tmpin, 0);
    dup2(tmpout, 1);
    close(tmpin);
    close(tmpout);
  
    int BUFSIZE = 1024;
    char* c = new char[BUFSIZE];
    int rd = read(pout[0], c, BUFSIZE);
    close(pout[0]);

    //printf("output is %d, %d, %s", BUFSIZE, rd, c);
    for (int i = rd - 12; i >= 0; --i ) {
      if (c[i] == '\n') {
        c[i] = '\t';
      }
      myunputc( c[i] );
    }
    delete c;
  }
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 244 "shell.l"
{
  /* Assume that file names have only alpha chars */
  yylval.cpp_string = new std::string(yytext);
  return WORD;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 249 "shell.l"
ECHO;
	YY_BREAK
#line 1595 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 195 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 195 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 194);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 249 "shell.l"
